### ISSUE TITLE
渗透测试问题发现

### ISSUE THREAD

**Issue by Mydearbaby** [KuroChan1998/Student-Information-Administration-System#3]
通过粗略的测试，该网站存在以下两个主要安全问题：
1、邮箱验证码绕过：在执行敏感操作时需要输入邮箱验证码，但可通过修改服务器返回包中的VeriftyCode的值绕过验证码的验证执行操作。
2、文件重复上传：在用户信息界面上传头像时，可以重复发送数据包，可造成服务器资源大量占用，引起安全问题。

**Comment by KuroChan1998** [comment]
非常感谢您的意见和建议~，我将尽快修复和加固，可以通过README下我的联系方式私信我哟

**Comment by amosjeek** [comment]
nice
