### ISSUE TITLE
图表无法显示。

### ISSUE THREAD

**Issue by weijingxuan** [KuroChan1998/Student-Information-Administration-System#6]
<script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/echarts.min.js"></script>链接地址无效。求解

**Comment by KuroChan1998** [comment]
echarts官方js资源库出了问题，F12调试报的是403。这些代码都是echarts的官方示例，5月份的时候做的功能是可以，10月份的时候就发现访问不了这些资源了。你可以尝试下载官方js库到本地，再引用本地资源

**Comment by KuroChan1998** [comment]
目前项目已更新，通过引用本地echarts资源~
